---
title: "Cause_o_Death"
output: slidy_presentation
author: Jorge Alejandro, Mia Alanis, Bryce Borak
---

```{r, echo = FALSE}
library(tidyverse)
library(shiny)

#setting up the datasets we will be using for our projects
  death_ds <- read.csv("cause_of_deaths.csv")
  popu_ds <- read.csv("world_population.csv")
  
  #The issue im having now is that ive realized that the years in the population data set are columns and the year in the deaths data set are rows. Im trying to figure out a way where we can have the population info combine with the death data set if the years match up, might have to be a question for the professor)

#Im going to add other columns that include things such as "Total recorded deaths" and a calculation for the crude death rate.
  death_ds %>% mutate(Total.Death = rowSums(death_ds[, -c(1:3)], na.rm = TRUE)) -> death_ds
  
#For a comprehensive dataset with population added to it, I made a join so we can analyse it further.
  dth_pplt_ds <- inner_join(death_ds, popu_ds, join_by(Country.Territory))
```

## What our dataset includes
- What represents the collumns?
- What are the rows?
```{r}
glimpse(death_ds)
glimpse(popu_ds)
```
Does mortality rate decrease as the years go by?

What countries would require the most medical funding and research?
(this question would require insight on deaths NOT caused by natural causes or "Accident")

## Graphs
Does mortality rate decrease as the years go by?
```{r, echo = FALSE}
death_ds %>% ggplot(aes(x = Year, y = Total.Death, )) + geom_point()
  #For this graph to be a little bit more legible, we either have to change what kind of graph we use, or we solve the first issue of trying to combine population with year and use the color of continent.

```

## Mia's Work
```{r,echo = FALSE}
#Mia's Work
#cleaning up / orginizing
 death_ds <- read.csv("cause_of_deaths.csv")
  popu_ds <- read.csv("world_population.csv")

#this is filters to just the years correlated to the population data set
death_ds_filtered <- death_ds %>% 
  filter(Year %in% c(1970, 1980, 1990, 2000, 2010, 2015, 2020, 2022))

combine_data <- inner_join(death_ds_filtered, popu_ds, join_by(Country.Territory))
```

```{r, echo = FALSE}
#Mia's Work
#filtering to only a single year and getting rid of population columns from other years
#1970 but does not have death info
data_of_1970 <- combine_data %>% 
  filter(Year == "1970") %>% 
  select(-c(X1990.Population, X1980.Population, X2000.Population, X2010.Population, X2015.Population, X2020.Population, X2022.Population))

#1980 but does not have death info
data_of_1980 <- combine_data %>% 
  filter(Year == "1980") %>% 
  select(-c(X1970.Population, X1990.Population, X2000.Population, X2010.Population, X2015.Population, X2020.Population, X2022.Population))

#1990
data_of_1990 <- combine_data %>% 
  filter(Year == "1990") %>% 
  select(-c(X1970.Population, X1980.Population, X2000.Population, X2010.Population, X2015.Population, X2020.Population, X2022.Population))

#2000
data_of_2000 <- combine_data %>% 
  filter(Year == "2000") %>% 
  select(-c(X1970.Population, X1980.Population, X1990.Population, X2010.Population, X2015.Population, X2020.Population, X2022.Population))

#2010
data_of_2010 <- combine_data %>% 
  filter(Year == "2010") %>% 
  select(-c(X1970.Population, X1980.Population, X2000.Population, X1990.Population, X2015.Population, X2020.Population, X2022.Population))

#2015
data_of_2015 <- combine_data %>% 
  filter(Year == "2015") %>% 
  select(-c(X1970.Population, X1980.Population, X2000.Population, X2010.Population, X1990.Population, X2020.Population, X2022.Population))

#2020 but does not have death info
data_of_2020 <- combine_data %>% 
  filter(Year == "2020") %>% 
  select(-c(X1970.Population, X1980.Population, X2000.Population, X2010.Population, X2015.Population, X1990.Population, X2022.Population))
  
#2022 but does not have death info
data_of_2022 <- combine_data %>% 
  filter(Year == "2022") %>% 
  select(-c(X1970.Population, X1980.Population, X1990.Population, X2010.Population, X2015.Population, X2020.Population, X2000.Population))
```

```{r, echo = FALSE}
#Mia's work
#answering the question
#What countries would require the most medical funding and research?
#(this question would require insight on deaths NOT caused by natural causes or "Accident")

#need to filter out deaths that arent natural causes or violent
non_diseases <- c("Drowning", "Interpersonal.Violence", "Drug.Use.Disorders", "Alcohol.Use.Disorders", "Self.harm", "Exposure.to.Forces.of.Nature", "Environmental.Heat.and.Cold.Exposure", "Conflict.and.Terrorism", "Road.Injuries", "Poisonings", "Fire..Heat..and.Hot.Substances", "Maternal.Disorders")

diseases <- death_ds %>% 
  select(-c(non_diseases, Year, Country.Territory, Code)) %>% 
  names()

#death data with just diseases
disease_deaths_data <- death_ds_filtered %>% 
  select(-c(non_diseases)) 

#this replaces "." in column names to " "
#save for the end because code wont work
#colnames(disease_deaths_data) <- gsub("\\.", " ", colnames(disease_deaths_data))

#death data with just diseases combine with population data
disease_data_pop <- inner_join(disease_deaths_data, popu_ds, join_by(Country.Territory))

#testing dataset with just diseases
new_1990_data <- data_of_1990 %>% select(-non_diseases)
new_2000_data <- data_of_2000 %>% select(-non_diseases)
new_2010_data <- data_of_2010 %>% select(-non_diseases)
new_2015_data <- data_of_2015 %>% select(-non_diseases)
```

```{r}
library(ggplot2)
#Mia's work
#testing a graph

ggplot(data = data_of_1990) + 
  geom_col(mapping = aes(x = Continent, y = Poisonings, fill = Continent))
 
ggplot(new_2010_data, aes(x = Continent))                       

#table
#new_2010_data %>%
  #select(Continent, Year, diseases)

```

```{r, echo = FALSE}
#code that orginzes each year long ways

library(tidyverse)
#2010
continent_data_2010 <- new_2010_data %>%
  group_by(Continent) %>%
  summarise(across(Meningitis:Acute.Hepatitis, sum, na.rm = TRUE))

long_data_2010 <- continent_data_2010 %>%
  pivot_longer(cols = Meningitis:Acute.Hepatitis, 
               names_to = "Disease", 
               values_to = "Deaths")
#1990
continent_data_1990 <- new_1990_data %>%
  group_by(Continent) %>%
  summarise(across(Meningitis:Acute.Hepatitis, sum, na.rm = TRUE))

long_data_1990 <- continent_data_1990 %>%
  pivot_longer(cols = Meningitis:Acute.Hepatitis, 
               names_to = "Disease", 
               values_to = "Deaths")

#2000
continent_data_2000 <- new_2000_data %>%
  group_by(Continent) %>%
  summarise(across(Meningitis:Acute.Hepatitis, sum, na.rm = TRUE))

long_data_2000 <- continent_data_2000 %>%
  pivot_longer(cols = Meningitis:Acute.Hepatitis, 
               names_to = "Disease", 
               values_to = "Deaths")

#2015
continent_data_2015 <- new_2015_data %>%
  group_by(Continent) %>%
  summarise(across(Meningitis:Acute.Hepatitis, sum, na.rm = TRUE))

long_data_2015 <- continent_data_2015 %>%
  pivot_longer(cols = Meningitis:Acute.Hepatitis, 
               names_to = "Disease", 
               values_to = "Deaths")
```

## Graph Code
```{r,echo = FALSE, fig.width=10, fig.height=10}
#code for each graph for each year in a facet wrap
#look at knit to see

#1990
continent_death_graph_1990 <- ggplot(long_data_1990, aes(x = reorder(Disease, Deaths), y = Deaths, fill = Disease)) +
  geom_col() +
  coord_flip() + # Makes long disease names easy to read
  facet_wrap(~Continent) + 
  theme_minimal() +
  theme(legend.position = "none") + # Hide legend since names are on the Y-axis
  labs(title = "1990 Global Disease Burden by Continent",
       x = "Disease",
       y = "Total Deaths")

#2000
continent_death_graph_2000 <- ggplot(long_data_2000, aes(x = reorder(Disease, Deaths), y = Deaths, fill = Disease)) +
  geom_col() +
  coord_flip() + # Makes long disease names easy to read
  facet_wrap(~Continent) + 
  theme_minimal() +
  theme(legend.position = "none") + # Hide legend since names are on the Y-axis
  labs(title = "2000 Global Disease Burden by Continent",
       x = "Disease",
       y = "Total Deaths")

#2010
continent_death_graph_2010 <- ggplot(long_data_2010, aes(x = reorder(Disease, Deaths), y = Deaths, fill = Disease)) +
  geom_col() +
  coord_flip() + # Makes long disease names easy to read
  facet_wrap(~Continent) + 
  theme_minimal() +
  theme(legend.position = "none") + # Hide legend since names are on the Y-axis
  labs(title = "2010 Global Disease Burden by Continent",
       x = "Disease",
       y = "Total Deaths")

#2015
continent_death_graph_2015 <- ggplot(long_data_2015, aes(x = reorder(Disease, Deaths), y = Deaths, fill = Disease)) +
  geom_col() +
  coord_flip() + # Makes long disease names easy to read
  facet_wrap(~Continent) + 
  theme_minimal() +
  theme(legend.position = "none") + # Hide legend since names are on the Y-axis
  labs(title = "2015 Global Disease Burden by Continent",
       x = "Disease",
       y = "Total Deaths")

continent_death_graph_1990
continent_death_graph_2000
continent_death_graph_2010
continent_death_graph_2015
```       

